---
type: zero-touch

# Set the left column width to 30%
default_width: 30
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

tabs:
- name: OpenShift Console
  url: 'https://console-openshift-console.${DOMAIN}'
- name: OpenShift AI
  url: 'https://data-science-gateway.${DOMAIN}'
- name: Terminal
  path: /terminal
  port: 443

antora:
  name: modules
  dir: www
  modules:
    - name: module-01-transportation-robot
      label: "Module 1: Transportation robot"
      scripts: [solve, validation]
      solveButton: true
    - name: module-02-rhoai-configuration
      label: "Module 2: Red Hat OpenShift AI configuration"
      scripts: [solve, validation]
      solveButton: true
    - name: module-03-model-training
      label: "Module 3: Model training"
      scripts: [solve, validation]
      solveButton: true
    - name: module-04-model-serving
      label: "Module 4: Model serving"
      scripts: [solve, validation]
      solveButton: true
    - name: module-05-pipeline-automation
      label: "Module 5: Pipeline automation"
      scripts: [solve, validation]
      solveButton: true
    - name: module-06-test-alerts
      label: "Module 6: Test alerts"
      scripts: [solve, validation]
      solveButton: true
