= Solving a Real-World Challenge: Our Case Study

Batteries play a crucial role in the current context of electric vehicles. But the definition of electric vehicles embraces not only electric cars, but also other types of autonomous vehicles such as those we can find operating in industrial facilities. Batteries act as the heart of these autonomous machines, and therefore, becomes one of the most critical components of the vehicle. An unexpected failure in one of the cells that composes the battery can lead to significant performance degradation and safety risks, potentially disrupting critical plant operations. And here is where Artificial Intelligence (AI) becomes a powerful ally.

== Developing an AI Solution for the Autonomous Vehicle

In this lab we will take the role of a systems engineer working for a logistics company aiming to enhance battery management and operations in autonomous vehicles operating within the plant. The team's mission is to create an end-to-end solution at the edge that covers two different scenarios:

=== Battery Monitoring System
In our electric vehicles we need to run an application responsible for monitoring the health of the battery during its various routes throughout the plant. This application also displays telemetry data collected from in-vehicle sensors such as voltage, temperature, driving distance or velocity via a graphical dashboard that can be monitored from the plant offices. In addition, this dashboard comes with an alerting system powered by AI models that are able to detect early signs of battery stress and predict potential failure.

To support this containerized solution inside our vehicle, a lightweight kubernetes platform is essential. This is where Red Hat Device Edge (MicroShift) comes into play.

=== Model Re-Training at the Edge
To ensure the AI models remain accurate and effective in detecting anomalies, they must be regularly updated with the latest data gathered from the vehicle during its operational routes. However, given the large volume of telemetry data generated during the vehicle's daily operations, it's impractical to continuously upload all of it over potentially unstable internet connections.

To overcome this challenge, the system collects the new data every 10 minutes. This data is then used to retrain the AI models on a more powerful edge server at the plant. For the entire AI/ML lifecycle, we rely on Red Hat OpenShift AI (RHOAI), deployed on a Single Node OpenShift (SNO) instance. The workflow is fully automated: a scheduled pipeline triggers the retraining of the models, followed by model validation. If the updated models outperform the existing ones, they are automatically deployed back to the vehicle, ensuring improved performance and smarter battery monitoring during plant operations.